### ISSUE TITLE
Doesn't sudo kextcache -u / still needed for the even better method?

### ISSUE THREAD

**Issue by andrewchen5678** [Temptin/Documents#1]
Doesn't `sudo kextcache -u /` still needed for the even better method? In your instruction it only ended in `sudo touch /System/Library/Extensions`

**Comment by Temptin** [comment]
@andrewchen5678 Nope, by touching /System/Library/Extensions you update the "modified date" of that folder. When OS X starts up, it detects this and rebuilds the cache. That's the official way of rebuilding the cache.

The kextcache -u / command is basically "force it to do that job *now*", and the only reason we do that during the manual method is so the user can verify that their kext-dev-mode is enabled. If they see the "allowing invalid signature" message, they know dev mode is on and they'll be able to boot without errors.
